Resipia/RECIPIA_RECIPE

- src/main/java/com/recipia/recipe/aws/AwsSqsListenerService.java
- src/main/java/com/recipia/recipe/dto/SnsInformationDto.java
- src/main/java/com/recipia/recipe/dto/SnsMessageDto.java
- src/main/java/com/recipia/recipe/event/sqseventlistener/RequestFeignListener.java
> RCP-160-Spring-Boot-aws-event-refactor

- src/main/resources/application.yml
> RCP-190-RECIPE-health-check-url-exclude-zipkin

- src/main/java/com/recipia/recipe/aws/AwsSqsListenerService.java
- src/main/java/com/recipia/recipe/dto/SnsMessageDto.java
- src/main/java/com/recipia/recipe/dto/message/MessageAttributesDto.java
- src/main/java/com/recipia/recipe/dto/message/MessageMemberIdDto.java
- src/main/java/com/recipia/recipe/dto/message/SnsNotificationDto.java
- src/main/java/com/recipia/recipe/dto/message/TraceIdDto.java
> Rcp 196 recipe sqs zipkin trace code refactor

- build.gradle
- src/main/java/com/recipia/recipe/config/SecurityConfig.java
- src/main/resources/application.yml
1. Grafana, Prometheus를 위한 설정을 진행했습니다.
> RCP-214-RECIPE-Grafana-Prometheus-setting

- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/main/java/com/recipia/recipe/common/exception/GlobalControllerAdvice.java
- src/main/java/com/recipia/recipe/common/exception/RecipeApplicationException.java
> RCP-231-RECIPE-Exception

- build.gradle
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/RecipeCreateRequestDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/SubCategoryEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeCategoryMapRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/SubCategoryEntityRepository.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/main/java/com/recipia/recipe/domain/SubCategory.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/dto/RecipeCreateRequestDtoTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/data.sql
> RCP-261-RECIPE-category-save

- src/main/java/com/recipia/recipe/adapter/in/search/MongoSearchController.java
- src/main/java/com/recipia/recipe/adapter/in/search/dto/SearchResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/mongo/MongoAdapter.java
- src/main/java/com/recipia/recipe/application/port/in/MongoUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/MongoPort.java
- src/main/java/com/recipia/recipe/application/service/MongoService.java
- src/test/java/com/recipia/recipe/adapter/in/search/MongoSearchControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/mongo/MongoAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/MongoServiceTest.java
1. 레시피 전체 검색기능 response 수정 (프론트 친화적으로 변경)
> Rcp 265 recipe all search

- src/main/java/com/recipia/recipe/adapter/in/listener/springevent/recipe/SpringEventRecipeCreateListener.java
- src/main/java/com/recipia/recipe/adapter/in/web/BookmarkController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/BookmarkDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/BookmarkRequestDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/mongo/MongoAdapter.java
- src/main/java/com/recipia/recipe/application/port/in/BookmarkUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/BookmarkPort.java
- src/main/java/com/recipia/recipe/application/port/out/MongoPort.java
- src/main/java/com/recipia/recipe/application/service/BookmarkService.java
- src/main/java/com/recipia/recipe/application/service/MongoService.java
- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/main/java/com/recipia/recipe/domain/Bookmark.java
- src/main/java/com/recipia/recipe/domain/converter/BookmarkConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/BookmarkControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/mongo/MongoAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/BookmarkServiceTest.java
- src/test/java/com/recipia/recipe/application/service/MongoServiceTest.java
- src/test/resources/application-test.yml
> RCP-270-RECIPE-bookmark

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeMainListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
> Rcp 268 recipe view detail

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/PagingResponseDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeMainListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeCategoryMapEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/data.sql
> RCP-266-RECIPE-READ

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeFileRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 레시피 업데이트에 soft delete 정책을 도입하기로 했는데 로직을 잘못 작성해서 수정작업을 진행함
2. del_yn을 변경시키는 방식으로 코드를 수정함
3. 테스트 코드를 작성하고 깨지는 테스트도 전부 수정함
> RCP-284-RECIPE-del_yn

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/RecipeCreateUpdateRequestDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/RecipeFileDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/SubCategoryDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeMainListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeFileRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/main/java/com/recipia/recipe/domain/RecipeFile.java
- src/main/java/com/recipia/recipe/domain/SubCategory.java
- src/main/java/com/recipia/recipe/domain/converter/CategoryConverter.java
- src/main/java/com/recipia/recipe/domain/converter/NutritionalInfoConverter.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeFileConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/dto/RecipeCreateUpdateRequestDtoTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 상세조회 코드 리팩토링 진행
2. 컨버터를 각각 명확하게 분리함
3. dto, domain 객체를 확실하게 분리
4. repository에서 querydsl을 사용할때는 N+1을 주의하고 Projection으로 dto를 받는 것으로 최적화 진행
> RCP-285-RECIPE-READ-refactoring

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeFileRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/DeleteRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/ImageS3Service.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/main/java/com/recipia/recipe/domain/converter/CategoryConverter.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeFileConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/dto/RecipeCreateUpdateRequestDtoTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 레시피 삭제기능 추가 (soft delete)
2. 업데이트/삭제하기 전에는 서비스에서 먼저 recipeId, memberId, del_yn을 통해 검증한 후 작업을 진행
3. 테스트 코드 작성 및 검증
> RCP-286-RECIPE-DELETE

- src/main/java/com/recipia/recipe/adapter/in/web/CommentController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/CommentListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/CommentUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/CommentPort.java
- src/main/java/com/recipia/recipe/application/service/CommentService.java
- src/test/java/com/recipia/recipe/adapter/in/web/CommentControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/CommentServiceTest.java
> Rcp 282 comment

- src/main/java/com/recipia/recipe/adapter/in/listener/springevent/RequestFeignListener.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/NicknameEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/NicknameAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/NicknameRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NicknameQuerydslRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/out/NicknamePort.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/feign/MemberChangedNicknameService.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/NicknameAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NicknameQuerydslRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/resources/application-test.yml
- src/test/resources/data.sql
1. 닉네임 엔티티 생성
2. recipe 엔티티에서 nickname 컬럼 제거
> RCP-295-RECIPE-NICKNAME-DB

- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeViewCntEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeViewCountRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RedisAdapter.java
- src/main/java/com/recipia/recipe/application/port/out/RedisPort.java
- src/main/java/com/recipia/recipe/application/service/RecipeLikeAndViewService.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RedisAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeLikeAndViewServiceTest.java
1. 레시피 조회수 기능 추가
2. 스케쥴러를 통해 1시간마다 동기화하는 로직 추가
> RCP-305-RECIPE-VIEW-COUNT

- src/main/java/com/recipia/recipe/adapter/in/web/CommentController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/CommentListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepository.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepositoryTest.java
1. 댓글 조회할때 멤버 닉네임 테이블에서 닉네임 가져오는 쿼리로 수정
> RCP-281-comment-subcomment

- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeLikeCntEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeLikeCountRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/service/RecipeLikeAndViewService.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RedisAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/resources/data.sql
> RCP-306-RECIPE-Redis-LikeCount

- src/main/java/com/recipia/recipe/adapter/in/listener/aws/SqsListenerService.java
- src/main/java/com/recipia/recipe/config/security/SecurityConfig.java
- src/main/resources/application-prod.yml
> RCP-313-RECIPE-SQS-Listener

- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/RecipeCreateUpdateRequestDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeFileRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/ImageS3Service.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/config/security/SecurityConfig.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/ImageS3ServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/application-test.yml
1. 이미지 수정로직 변경 (매번 모든 이미지를 삭제하면 엄청난 리소스의 낭비가 예상되어 로직 변경)
> RCP-309-RECIPE-IMAGE-REFACTOR

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
> [RCP-324] :recycle: 서브 카테고리를 가져오는 로직 수정

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/config/security/SecurityConfig.java
- src/main/java/com/recipia/recipe/config/security/filter/JwtAuthorizationFilter.java
- src/main/java/com/recipia/recipe/config/security/jwt/TokenValidator.java
- src/main/resources/application-prod.yml
1. 서브 카테고리 로직 수정
2. 디버깅 레벨 수정
3. 스프링 시큐리티에서 jwt 활성화
> RCP-323-RECIPE-bug-fix

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeMainListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/CategorySubMapEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/SubCategoryEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/data.sql
1. 북마크 여부를 boolean으로 가져오던걸 bookmark id로 수정
2. 서브 카테고리 명 가져올때 foreach 돌려서 List<String>로 가져오는걸로 수정
3. 서브 카테고리로 검색 옵션 추가
> RCP-322-RECIPE-CTGRY-SELECT

- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
> RCP-328-RECIPE-DETAIL-VEW-REFACTOR

- src/main/java/com/recipia/recipe/adapter/in/listener/aws/SqsListenerService.java
- src/main/java/com/recipia/recipe/adapter/in/listener/springevent/RequestFeignListener.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/NicknameAdapter.java
- src/main/java/com/recipia/recipe/application/port/in/FeignClientUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/NicknamePort.java
- src/main/java/com/recipia/recipe/application/service/feign/MemberChangedNicknameService.java
- src/main/java/com/recipia/recipe/common/event/SignUpEvent.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/NicknameAdapterTest.java
> RCP-341-RECIPE-SQS-REFACTOR

- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewResponseDto.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
1. 레시피 상세조회에서 memberId를 받도록 수정
> RCP-348-RECIPE-memberId-Refactor

- src/main/java/com/recipia/recipe/adapter/in/web/MyPageController.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeRepository.java
- src/main/java/com/recipia/recipe/application/port/in/MyPageUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/MyPageService.java
- src/main/java/com/recipia/recipe/domain/MyPage.java
- src/test/java/com/recipia/recipe/adapter/in/web/MyPageControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/MyPageServiceTest.java
> RCP-347-MYPAGE-RCP-COUNT

- src/main/java/com/recipia/recipe/adapter/in/web/MyPageController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeMainListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/MyPageUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/MyPageService.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/MyPageServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/data.sql
1. 내가 작성한 레시피중 조회수 높은순으로 5개 가져오기
> RCP-351-MY-HIGH-VIEW

- src/main/java/com/recipia/recipe/adapter/in/listener/springevent/recipe/SpringEventRecipeCreateListener.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/RecipeCreateUpdateRequestDto.java
> RCP-354-RECIPE-NPE

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
> RCP-353-RECIPE-MAIL-THUMBNAIL

- src/main/java/com/recipia/recipe/adapter/in/web/MyPageController.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/MyPageUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/MyPageService.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/in/web/MyPageControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/MyPageServiceTest.java
> Rcp 356 my recipe

- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/main/java/com/recipia/recipe/common/exception/GlobalControllerAdvice.java
1. 에러코드 재정의
2. Global Controller Advice에 Valid 예외처리 코드 추가
> RCP-359-RECIPE-ERROR-CODE

- src/main/java/com/recipia/recipe/adapter/in/web/MyPageController.java
- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/MyPageRequestDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/MyPageUseCase.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/MyPageService.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/common/exception/ErrorCode.java
- src/main/java/com/recipia/recipe/common/exception/GlobalControllerAdvice.java
- src/test/java/com/recipia/recipe/adapter/in/web/MyPageControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/MyPageServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/data.sql
1. 내가 북마크한 레시피 목록 가져오기
2. 내가 작성한 레시피 갯수, 내가 작성한 레시피중 조회수 높은 5개 가져오기 api에서 파라미터 currentMemberId -> targetMemberId로 수정
> Rcp 357 my bookmark

- src/main/java/com/recipia/recipe/adapter/in/web/MyPageController.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/MyPageUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/MyPageService.java
1. 내가 좋아요한 레시피 목록
2. MyPage에서 레시피 목록 가져오는 과정에서 썸네일 있으면 preUrl 세팅해주는 메서드를 내부메서드로 추출
> Rcp 358 like recipe

- src/main/java/com/recipia/recipe/application/service/ImageS3Service.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/application/service/ImageS3ServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 이미지 저장될때 file order 순차적으로 증가하도록 코드 수정
> RCP-361-RECIPE-IMAGE-BUG-FIX

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeLikeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeLikeRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/BookmarkQuerydslRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeLikeQuerydslRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/out/BookmarkPort.java
- src/main/java/com/recipia/recipe/application/port/out/RecipeLikePort.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/BookmarkAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeLikeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/BookmarkQuerydslRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeLikeQuerydslRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
- src/test/resources/data.sql
1. 레시피 삭제하면 동시에 레시피 파일, 북마크, 좋아요 삭제
> RCP-363-RECIPE-DELETE

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/SubCommentRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NicknameQuerydslRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NutritionalInfoQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeCategoryMapQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/SubCommentQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/out/CommentPort.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NutritionalInfoQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeCategoryMapQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/SubCommentQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 레시피 삭제할때 영양소, 카테고리 맵핑, 댓글, 대댓글 전부 삭제처리
> RCP-365-RECIPE-MISSED-DELETE

- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/CommentListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepository.java
- src/test/java/com/recipia/recipe/adapter/in/web/CommentControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/CommentServiceTest.java
1. 댓글 목록 가져올때 댓글에 대댓글 갯수 포함해서 반환
> RCP-366-RECIPE-SUB-COMMENT-COUNT

- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewResponseDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/service/MyPageService.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/MyPageControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/MyPageServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 레시피 목록에 생성일 필드 추가
2. 레시피 상세에 생성일 필드 추가
> RCP-368-RECIPE-LIST-CREATEDATE

- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/SubCommentQueryRepository.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepositoryTest.java
1. querydsl로 업데이트했을때 updateDttm 자동으로 업데이트 안돼서 수동으로 update문에 set 추가
> RCP-370--querydsl-updateDttm

- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/CommentListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeListResponseDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/CommentQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/test/java/com/recipia/recipe/adapter/in/web/CommentControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/MyPageControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/CommentAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/CommentServiceTest.java
- src/test/java/com/recipia/recipe/application/service/MyPageServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 댓글, 대댓글, 레시피 생성일 전부 String으로 반환하는 로직으로 수정
> RCP-371-RECIPE-COMMENT-LocalDateTime

- src/main/java/com/recipia/recipe/adapter/in/listener/springevent/RequestFeignListener.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/NicknameAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NicknameQuerydslRepository.java
- src/main/java/com/recipia/recipe/application/port/in/NicknameUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/NicknamePort.java
- src/main/java/com/recipia/recipe/application/service/MemberWithdrawService.java
- src/main/java/com/recipia/recipe/application/service/feign/MemberChangedNicknameService.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/NicknameQuerydslRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/MemberWithdrawServiceTest.java
1. 회원 탈퇴시 닉네임 삭제
2. 회원 탈퇴 서비스 테스트 코드
> RCP-367-MEMBER-WITHDRAW-SQS

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/application/port/in/ReadRecipeUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipePort.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/in/web/dto/request/CommentUpdateRequestDtoTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepositoryTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. 레시피 목록에 레시피 이름에 해당하는 목록 가져오기
> RCP-388-RECIPE-SEARCH

- src/main/java/com/recipia/recipe/adapter/in/web/dto/response/RecipeDetailViewResponseDto.java
- src/main/java/com/recipia/recipe/application/port/in/RecipeLikeUseCase.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
> RCP-391-RECIPE-LIKE

- src/main/java/com/recipia/recipe/adapter/in/web/RecipeController.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RedisAdapter.java
- src/main/java/com/recipia/recipe/application/port/out/RedisPort.java
- src/main/java/com/recipia/recipe/application/service/RecipeLikeService.java
- src/main/java/com/recipia/recipe/application/service/RecipeService.java
- src/main/java/com/recipia/recipe/domain/Recipe.java
- src/main/java/com/recipia/recipe/domain/converter/RecipeConverter.java
- src/test/java/com/recipia/recipe/adapter/in/web/RecipeControllerTest.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeAdapterTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeLikeServiceTest.java
- src/test/java/com/recipia/recipe/application/service/RecipeServiceTest.java
1. Redis 조회수 기능 보강
2. 상세보기를 할 때 조회수를 저장하고 가져오도록 로직 수정
> Rcp 394 recipe redis view

- src/main/java/com/recipia/recipe/adapter/in/web/dto/request/RecipeViewCountDto.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeLikeCountEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistence/entity/RecipeViewCountEntity.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeLikeCountRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeViewCountAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RecipeViewCountRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/RedisAdapter.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeQueryRepository.java
- src/main/java/com/recipia/recipe/adapter/out/persistenceAdapter/querydsl/RecipeViewCountQueryDslRepository.java
- src/main/java/com/recipia/recipe/application/port/in/SyncViewCountUseCase.java
- src/main/java/com/recipia/recipe/application/port/out/RecipeViewCountPort.java
- src/main/java/com/recipia/recipe/application/port/out/RedisPort.java
- src/main/java/com/recipia/recipe/application/service/RecipeLikeService.java
- src/main/java/com/recipia/recipe/application/service/SyncViewCountService.java
- src/main/java/com/recipia/recipe/config/redis/SchedulerConfig.java
- src/test/java/com/recipia/recipe/adapter/out/persistenceAdapter/RedisAdapterTest.java
1. 레디스 RDB 정합성을 위한 코드 추가
2. 스케쥴러 코드 추가
3. 배치 코드에서 save부분에 대한 추가 로직이 필요함
> Rcp 393 recipe redis rdb
